version: '2'

# There should be an environment variable called SLACK_URL

services:
    monitoring:
        restart: unless-stopped
        build:
            context: .
        image: bisq:monitoring
        container_name: monitoring
        ports:
          - 8080:8080
        environment:
          - SLACK_PRICE_URL
          - SLACK_SEED_URL
          - SLACK_BTC_URL

